
SETTE_AND_TABLE = {
    (0, 1): 1,
    (0, -1): -1,
    (-1, 0): -1,
    (1, 1): 1,
    (-1, 1): -1,
    (1, 0): 1,
    (0, 0): 1,
    (-1, -1): -1,
    (1, -1): -1,
}

SETTE_OR_TABLE = {
    (0, 1): 1,
    (0, -1): -1,
    (-1, 0): -1,
    (-1, 1): 1,
    (1, 1): 1,
    (1, 0): 1,
    (0, 0): -1,
    (-1, -1): -1,
    (1, -1): 1,
}

def sette_and(a: int, b: int) -> int:
    return SETTE_AND_TABLE[(a, b)]


def sette_or(a: int, b: int) -> int:
    return SETTE_OR_TABLE[(a, b)]


def sette_not(x: int) -> int:
    return -x


def sette_xor(a: int, b: int) -> int:
    ab_or = sette_or(a, b)
    ab_and = sette_and(a, b)
    not_and = sette_not(ab_and)
    return sette_and(ab_or, not_and)

def sette_add(a: int, b: int, carry: int):

    ab_xor = sette_xor(a, b)
    sum_digit = sette_xor(ab_xor, carry)

    gen = sette_and(a, b)        # carry generated by a,b
    prop = sette_and(carry, ab_xor)  # propagate carry
    carry_out = sette_or(gen, prop)

    return sum_digit, carry_out

def sette_ripple_add(vecs):
    if not vecs:
        return [-1] * 4

    result = vecs[0].copy()
    carry = -1

    for vec in vecs[1:]:
        L = max(len(result), len(vec))
        A = result + [0] * (L - len(result))
        B = vec + [0] * (L - len(vec))

        new_res = []
        local_carry = carry

        for a, b in zip(A, B):
            s, local_carry = sette_add(a, b, local_carry)
            new_res.append(s)

        result = new_res
        carry = local_carry

    if carry != -1:
        result.append(carry)

    return result
